spring:
  cloud:
    aws:
      region:
        static: eu-central-1
      dynamodb:
        endpoint: ${DYNAMO_DB_ENDPOINT}
  servlet:
    multipart:
      max-file-size: 4MB
aws:
  bucket-name: ${BUCKET_NAME}
  task-queue-sqs: ${TASK_QUEUE_SQS}
